language: ruby
sudo: false
cache: bundler
rvm:
  - 2.4.1
  - 2.3.4
  - 2.2
  - 2.1
  - 2.0
  - ruby-head
  - jruby-9.1
  - jruby-head
env:
  global:
    - JRUBY_OPTS="--debug"
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  fast_finish: true
before_install: gem install bundler -v 1.14.6
